load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_rust_toolchain(
    name = "rust",
    exec_compatible_with = select({
        "bootstrap//constraints:stage0": ["bootstrap//constraints:stage0"],
        "bootstrap//constraints:stage1": ["bootstrap//constraints:stage1"],
        "bootstrap//constraints:stage2": ["bootstrap//constraints:stage2"],
    }),
    visibility = ["PUBLIC"],
)
